// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentRepo.Server.Data;

#nullable disable

namespace StudentRepo.Server.Migrations
{
    [DbContext(typeof(StudentContext))]
    [Migration("20240716003328_NewStudents")]
    partial class NewStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentRepo.Server.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("NIC")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St, Anytown, USA",
                            DateOfBirth = new DateTime(2000, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            Mobile = "1234567890",
                            NIC = "123456789V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Oak St, Anytown, USA",
                            DateOfBirth = new DateTime(2001, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "jane.doe@example.com",
                            FirstName = "Jane",
                            LastName = "Doe",
                            Mobile = "0987654321",
                            NIC = "987654321V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Pine St, Anytown, USA",
                            DateOfBirth = new DateTime(1999, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "alice.smith@example.com",
                            FirstName = "Alice",
                            LastName = "Smith",
                            Mobile = "1122334455",
                            NIC = "112233445V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 4,
                            Address = "101 Maple St, Anytown, USA",
                            DateOfBirth = new DateTime(1998, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "bob.brown@example.com",
                            FirstName = "Bob",
                            LastName = "Brown",
                            Mobile = "2233445566",
                            NIC = "223344556V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 5,
                            Address = "202 Cedar St, Anytown, USA",
                            DateOfBirth = new DateTime(1997, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "charlie.davis@example.com",
                            FirstName = "Charlie",
                            LastName = "Davis",
                            Mobile = "3344556677",
                            NIC = "334455667V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 6,
                            Address = "303 Birch St, Anytown, USA",
                            DateOfBirth = new DateTime(2002, 6, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "diana.evans@example.com",
                            FirstName = "Diana",
                            LastName = "Evans",
                            Mobile = "4455667788",
                            NIC = "445566778V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 7,
                            Address = "404 Spruce St, Anytown, USA",
                            DateOfBirth = new DateTime(1996, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "edward.frank@example.com",
                            FirstName = "Edward",
                            LastName = "Frank",
                            Mobile = "5566778899",
                            NIC = "556677889V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 8,
                            Address = "505 Elm St, Anytown, USA",
                            DateOfBirth = new DateTime(2003, 8, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "fiona.green@example.com",
                            FirstName = "Fiona",
                            LastName = "Green",
                            Mobile = "6677889900",
                            NIC = "667788990V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 9,
                            Address = "606 Ash St, Anytown, USA",
                            DateOfBirth = new DateTime(2004, 9, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "george.harris@example.com",
                            FirstName = "George",
                            LastName = "Harris",
                            Mobile = "7788990011",
                            NIC = "778899001V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 10,
                            Address = "707 Willow St, Anytown, USA",
                            DateOfBirth = new DateTime(2005, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "hannah.iverson@example.com",
                            FirstName = "Hannah",
                            LastName = "Iverson",
                            Mobile = "8899001122",
                            NIC = "889900112V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 11,
                            Address = "808 Poplar St, Anytown, USA",
                            DateOfBirth = new DateTime(1995, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ian.jackson@example.com",
                            FirstName = "Ian",
                            LastName = "Jackson",
                            Mobile = "9900112233",
                            NIC = "990011223V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 12,
                            Address = "909 Walnut St, Anytown, USA",
                            DateOfBirth = new DateTime(2006, 12, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "julia.king@example.com",
                            FirstName = "Julia",
                            LastName = "King",
                            Mobile = "0011223344",
                            NIC = "001122334V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 13,
                            Address = "1010 Cherry St, Anytown, USA",
                            DateOfBirth = new DateTime(1994, 1, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "kevin.lewis@example.com",
                            FirstName = "Kevin",
                            LastName = "Lewis",
                            Mobile = "1122334455",
                            NIC = "112233445V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 14,
                            Address = "1111 Pineapple St, Anytown, USA",
                            DateOfBirth = new DateTime(2007, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "laura.miller@example.com",
                            FirstName = "Laura",
                            LastName = "Miller",
                            Mobile = "2233445566",
                            NIC = "223344556V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 15,
                            Address = "1212 Coconut St, Anytown, USA",
                            DateOfBirth = new DateTime(2008, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "michael.nelson@example.com",
                            FirstName = "Michael",
                            LastName = "Nelson",
                            Mobile = "3344556677",
                            NIC = "334455667V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 16,
                            Address = "1313 Orange St, Anytown, USA",
                            DateOfBirth = new DateTime(2009, 4, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "nina.olsen@example.com",
                            FirstName = "Nina",
                            LastName = "Olsen",
                            Mobile = "4455667788",
                            NIC = "445566778V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 17,
                            Address = "1414 Lemon St, Anytown, USA",
                            DateOfBirth = new DateTime(2010, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "oscar.perez@example.com",
                            FirstName = "Oscar",
                            LastName = "Perez",
                            Mobile = "5566778899",
                            NIC = "556677889V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 18,
                            Address = "1515 Grapefruit St, Anytown, USA",
                            DateOfBirth = new DateTime(2011, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "paula.quinn@example.com",
                            FirstName = "Paula",
                            LastName = "Quinn",
                            Mobile = "6677889900",
                            NIC = "667788990V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 19,
                            Address = "1616 Watermelon St, Anytown, USA",
                            DateOfBirth = new DateTime(2012, 7, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "quincy.roberts@example.com",
                            FirstName = "Quincy",
                            LastName = "Roberts",
                            Mobile = "7788990011",
                            NIC = "778899001V",
                            ProfileImage = ""
                        },
                        new
                        {
                            Id = 20,
                            Address = "1717 Blueberry St, Anytown, USA",
                            DateOfBirth = new DateTime(2013, 8, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "rachel.smith@example.com",
                            FirstName = "Rachel",
                            LastName = "Smith",
                            Mobile = "8899001122",
                            NIC = "889900112V",
                            ProfileImage = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
